-- MySQL Workbench Synchronization
-- Generated: 2021-02-08 15:58
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: adr

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`USUARIOS` (
  `idUSUARIO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `url_foto` VARCHAR(45) NULL DEFAULT NULL,
  `nick` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `idDISTRITO` INT(11) NOT NULL,
  `idContacto` INT(11) NOT NULL,
  PRIMARY KEY (`idUSUARIO`),
  INDEX `fk_USUARIOS_DISTRITOS1_idx` (`idDISTRITO` ASC),
  INDEX `fk_USUARIOS_Contacto1_idx` (`idContacto` ASC),
  CONSTRAINT `fk_USUARIOS_DISTRITOS1`
    FOREIGN KEY (`idDISTRITO`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`DISTRITOS` (`idDISTRITO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_Contacto1`
    FOREIGN KEY (`idContacto`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`Contacto` (`idContacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`WORKERS` (
  `idWORKER` INT(11) NOT NULL AUTO_INCREMENT,
  `idUSUARIO` INT(10) UNSIGNED NOT NULL,
  `idSERVICIO` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idWORKER`),
  INDEX `fk_WORKERS_USUARIOS1_idx` (`idUSUARIO` ASC),
  INDEX `fk_WORKERS_SERVICIOS1_idx` (`idSERVICIO` ASC),
  CONSTRAINT `fk_WORKERS_USUARIOS1`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`USUARIOS` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WORKERS_SERVICIOS1`
    FOREIGN KEY (`idSERVICIO`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`SERVICIOS` (`idSERVICIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`CLIENTES` (
  `idCLIENTE` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `idUSUARIO` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCLIENTE`),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`idUSUARIO` ASC),
  CONSTRAINT `fk_CLIENTES_USUARIOS1`
    FOREIGN KEY (`idUSUARIO`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`USUARIOS` (`idUSUARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`SERVICIOS` (
  `idSERVICIO` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `tarifa` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idSERVICIO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`CONTRATOS` (
  `idCONTRATO` INT(11) NOT NULL AUTO_INCREMENT,
  `estado` VARCHAR(45) NOT NULL,
  `idWORKER` INT(11) NOT NULL,
  `idCLIENTE` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCONTRATO`),
  INDEX `fk_CONTRATOS_WORKERS_idx` (`idWORKER` ASC),
  INDEX `fk_CONTRATOS_CLIENTES1_idx` (`idCLIENTE` ASC),
  CONSTRAINT `fk_CONTRATOS_WORKERS`
    FOREIGN KEY (`idWORKER`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`WORKERS` (`idWORKER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONTRATOS_CLIENTES1`
    FOREIGN KEY (`idCLIENTE`)
    REFERENCES `bvj4hzascbyeihgwfuro`.`CLIENTES` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`DISTRITOS` (
  `idDISTRITO` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDISTRITO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `bvj4hzascbyeihgwfuro`.`Contacto` (
  `idContacto` INT(11) NOT NULL AUTO_INCREMENT,
  `telefono_fijo` INT(11) NULL DEFAULT NULL,
  `telefono_celuldar` INT(11) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idContacto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

DROP TABLE IF EXISTS `bvj4hzascbyeihgwfuro`.`users` ;

DROP TABLE IF EXISTS `bvj4hzascbyeihgwfuro`.`news` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
